import type { Part } from '@/lib/types';

export const initialParts: Omit<Part, 'id'>[] = [
  {
    name: 'M8x50 Hex Bolt',
    partNumber: 'PN-BLT-M8-50',
    description: 'Standard 50mm M8 hex bolt, zinc plated.',
    supplier: 'BoltCorp',
    location: 'Bin A-12',
    category: 'Fasteners',
    quantity: 150,
    minStock: 50,
    maxStock: 200,
    stockHistory: [],
  },
  {
    name: '1/4" Lock Washer',
    partNumber: 'PN-WSH-14-LK',
    description: 'Split lock washer for 1/4" bolts.',
    supplier: 'Fastener Inc.',
    location: 'Drawer 3-C',
    category: 'Fasteners',
    quantity: 500,
    minStock: 200,
    maxStock: 1000,
    stockHistory: [],
  },
  {
    name: 'Hydraulic Filter',
    partNumber: 'HF-2875A',
    description: 'High-pressure hydraulic fluid filter element.',
    supplier: 'FilterSolutions',
    location: 'Shelf B-2',
    category: 'Filters',
    quantity: 25,
    minStock: 10,
    maxStock: 40,
    stockHistory: [],
  },
  {
    name: 'Drive Belt 4L320',
    partNumber: 'DB-4L320',
    description: 'V-belt for main conveyor motor.',
    supplier: 'PowerTrans',
    location: 'Hanger 5',
    category: 'Mechanical',
    quantity: 8,
    minStock: 5,
    maxStock: 20,
    stockHistory: [],
  },
  {
    name: 'E-Stop Button',
    partNumber: 'ES-24V-RED',
    description: '24V emergency stop push button with NC contact.',
    supplier: 'ControlSys',
    location: 'Cabinet 7-E',
    category: 'Electrical',
    quantity: 12,
    minStock: 5,
    maxStock: 20,
    stockHistory: [],
  },
  {
    name: 'Proximity Sensor',
    partNumber: 'PS-M12-NPN-NO',
    description: 'M12 NPN Normally Open inductive proximity sensor.',
    supplier: 'SensorTech',
    location: 'Cabinet 7-F',
    category: 'Electrical',
    quantity: 18,
    minStock: 10,
    maxStock: 30,
    stockHistory: [],
  },
  {
    name: '2" Ball Valve',
    partNumber: 'BV-SS-200',
    description: 'Stainless steel 2" NPT ball valve, full port.',
    supplier: 'FlowControl',
    location: 'Shelf C-1',
    category: 'Pneumatics',
    quantity: 5,
    minStock: 4,
    maxStock: 10,
    stockHistory: [],
  },
];
